version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ProjectJavaCard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo12
    volumes:
      - db-data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
volumes:
  db-data: